### ISSUE TITLE
Support scanning all namespaces

### ISSUE THREAD

**Issue by gbrayut** [edrevo/suspicious-pods#1]
For cluster administrators it would be nice to have an option to scan all namespaces (similar to the --all-namespaces argument in kubectl). For instance I currently find unschedulable pods using:

`kubectl get pods --all-namespaces --field-selector status.phase!=Running -o wide --sort-by=.metadata.creationTimestamp`

which works pretty well but still includes Completed containers from cronjobs. This tool would work better, but we have a lot of namespaces so scanning each one individually is difficult.

The output format might also need a header or column to indicate which namespace the pod is from.

**Comment by edrevo** [comment]
Thanks for the feedback! Fixed in [release 0.6.0](https://github.com/edrevo/suspicious-pods/releases/tag/0.6.0)!

cc @rndmh3ro @jabrown85 @derekperkins @usualstuff since they upvoted the issue
