### ISSUE TITLE
Fails on Kubernetes v1.15.9

### ISSUE THREAD

**Issue by joberget** [edrevo/suspicious-pods#3]
Version 0.6 on Linux. It works on v1.15.6.

I get the following:

$ ./suspicious-pods --all-namespaces
Error: Error { inner:

ApiError https://server//api/v1/pods?: Client Error: 404 Not Found ("Error(Status(404), \"https://server//api/v1/pods?\")") }

**Comment by edrevo** [comment]
Sorry for the delay. Do you have the KUBECONFIG variable set to a valid kubeconfig file? What's the output of `kubectl cluster-info`?

**Comment by joberget** [comment]
Sorry for late reply I get the following now on my Mac:

 $ rustc --version
rustc 1.41.1

`$ export RUST_BACKTRACE=full; suspicious-pods --all-namespaces`

`thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1190:5
stack backtrace:
   0:        0x107acccb2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66f38d4abb2e41c1
   1:        0x107899b20 - core::fmt::write::h4f487e714088986d
   2:        0x107acc3eb - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x107acc045 - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x107acb773 - std::panicking::rust_panic_with_hook::h0c4b67125f55410a
   5:        0x107ad003e - std::panicking::continue_panic_fmt::h0e74ab2b215a1401
   6:        0x107adebf9 - rust_begin_unwind
   7:        0x107896f87 - core::panicking::panic_fmt::h09741a3213dba543
   8:        0x10789a07e - core::option::expect_failed::hd2186856cb53bb16
   9:        0x107968071 - kube::config::apis::AuthInfo::load_gcp::h5e05a671080b209e
  10:        0x10794d6fa - kube::config::create_client_builder::h0fe207eab2652cc5
  11:        0x107b458bb - suspicious_pods_lib::setup_k8s_client::h5f9380248c23b400
  12:        0x107ae429c - suspicious_pods::main::h2f02317a2ea80ea6
  13:        0x107ae3096 - std::rt::lang_start::{{closure}}::hd460b8584c668402
  14:        0x107ae34c7 - main`

**Comment by edrevo** [comment]
Sorry for the delay. Should be fixed in the 1.0 release! Please do reopen the issue if it still doesn't work. Thanks for the report!
